openapi: 3.0.3

info:
  title: Flight Logger API
  version: 0.0.1
  description: A simple server to log commercial flights

servers:
  - url: http://localhost:8080/api
    description: Local development server

paths:
  /airlines:
    $ref: './domain/airline/paths/airlines.yaml'
  /airlines/{airlineIcao}:
    $ref: './domain/airline/paths/airlinesByIcao.yaml'
  /countries:
    $ref: './domain/country/paths/countries.yaml'
  /countries/{id}:
    $ref: './domain/country/paths/countriesById.yaml'
  /airports:
    $ref: './domain/airport/paths/airports.yaml'
  /airports/{icao}:
    $ref: './domain/airport/paths/airportByIcao.yaml'
